In [1]:
from sklearn.datasets import make_regression
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X, y, coef = make_regression(n_samples=100, n_features=2, noise=5, random_state=42, coef=True)

In [3]:
coef

array([87.73730719, 74.07686178])

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [8]:
class LinearRegCustom:
      
    def fit(self, X, y):
        
        X = np.hstack([np.ones((X.shape[0], 1)), X])
        
        y = y.reshape(-1, 1)
        
        first = np.linalg.inv(np.dot(X.T, X))
        second = np.dot(X.T, y)
        
        self.theta_ = np.dot(first, second)

    def predict(self, X):
        X = np.hstack([np.ones((X.shape[0], 1)), X])
        return np.dot(X, self.theta_)

In [9]:
m2 = LinearRegCustom()
m2.fit(X_train, y_train)

In [10]:
m2.predict(X_test[:10])

array([[ -57.84868392],
       [  -1.04944718],
       [  84.33670533],
       [ -20.56781838],
       [  67.08540561],
       [ 114.07948749],
       [ 193.92679419],
       [-127.12256719],
       [-185.12788784],
       [ -55.45145508]])

In [11]:
y_test[:10]

array([ -53.96917117,    1.57590327,   83.23474413,  -26.98206658,
         68.78873855,  125.76670994,  190.71591107, -115.26779066,
       -188.93608596,  -52.57567661])

In [12]:
m2.predict(X_test[:10])

array([[ -57.84868392],
       [  -1.04944718],
       [  84.33670533],
       [ -20.56781838],
       [  67.08540561],
       [ 114.07948749],
       [ 193.92679419],
       [-127.12256719],
       [-185.12788784],
       [ -55.45145508]])