In [1]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input

from sklearn.datasets import make_blobs

import numpy as np

import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [2]:
data = np.load("../datasets/mnist/mnist_train_small.npy")

In [3]:
X, y = data[:, 1:], data[:, 0]

In [4]:
y_hot = OneHotEncoder().fit_transform(y.reshape(-1, 1)).todense()

In [8]:
y_hot_oe = OneHotEncoder().fit_transform((y % 2).reshape(-1, 1)).todense()

In [21]:
(y%2)

array([1, 1, 1, ..., 0, 1, 1], dtype=uint8)

In [12]:
y_hot_oe[:10]

matrix([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])

In [13]:
in_layer = Input(shape=(784,))
d1 = Dense(400, activation="sigmoid", name="l1")(in_layer)
d2 = Dense(200, activation="sigmoid", name="l2")(d1)
d3 = Dense(100, activation="sigmoid", name="l3")(d2)
d41 = Dense(50, activation="sigmoid", name="l41")(d3)
d42 = Dense(50, activation="sigmoid", name="l42")(d3)
out_layer_1 = Dense(10, activation="softmax", name="o1")(d41)
out_layer_2 = Dense(2, activation="softmax", name="o2")(d42)

model = Model(inputs=[in_layer], outputs=[out_layer_1, out_layer_2])

In [14]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 784)]        0                                            
__________________________________________________________________________________________________
l1 (Dense)                      (None, 400)          314000      input_3[0][0]                    
__________________________________________________________________________________________________
l2 (Dense)                      (None, 200)          80200       l1[0][0]                         
__________________________________________________________________________________________________
l3 (Dense)                      (None, 100)          20100       l2[0][0]                         
____________________________________________________________________________________________

In [15]:
model.compile(optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"])

In [17]:
outcome = model.fit(X, [y_hot, y_hot_oe], epochs=10)

Train on 19999 samples
Epoch 1/10
19999/19999 [==============================] - 10s 512us/sample - loss: 1.4098 - o1_loss: 1.1342 - o2_loss: 0.2756 - o1_accuracy: 0.6691 - o2_accuracy: 0.8825
Epoch 2/10
19999/19999 [==============================] - 8s 423us/sample - loss: 0.6833 - o1_loss: 0.5020 - o2_loss: 0.1813 - o1_accuracy: 0.8545 - o2_accuracy: 0.9317
Epoch 3/10
19999/19999 [==============================] - 9s 433us/sample - loss: 0.5611 - o1_loss: 0.4021 - o2_loss: 0.1590 - o1_accuracy: 0.8780 - o2_accuracy: 0.9418
Epoch 4/10
19999/19999 [==============================] - 9s 451us/sample - loss: 0.5356 - o1_loss: 0.3778 - o2_loss: 0.1578 - o1_accuracy: 0.8868 - o2_accuracy: 0.9417
Epoch 5/10
19999/19999 [==============================] - 9s 437us/sample - loss: 0.5238 - o1_loss: 0.3724 - o2_loss: 0.1514 - o1_accuracy: 0.8852 - o2_accuracy: 0.9437
Epoch 6/10
19999/19999 [==============================] - 9s 428us/sample - loss: 0.4910 - o1_loss: 0.3434 - o2_loss: 0.1476 - o1_a

In [24]:
o1, o2 = model.predict(X[:5])

In [26]:
o1.argmax(axis=1)

array([5, 7, 9, 5, 2])

In [27]:
o2.argmax(axis=1)

array([1, 1, 1, 1, 0])