In [1]:
import numpy as np

In [2]:
a = np.array([1, 3, 6, 9])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(4,)

In [10]:
a.reshape(2, 1, 2)

array([[[1, 3]],

       [[6, 9]]])

In [16]:
np.zeros((4, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.empty((4, 4), dtype=int)

array([[                   0,                    0,                    0,
                           0],
       [                   0,                    0,                    0,
         2484135899465670501],
       [-4611686018427387904, -4611686018427387904,  8319104481852391443,
         7017771752431185769],
       [ 3471486280774410850,  3559079995691525217,  3474305222499906610,
         2478164403814806320]])